# 8. 예외처리

## 1. 예외처리(exception handling)

+ 1.1 프로그램 오류
  + 프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우가 있는데, 이러한 결과를 초래하는 원인을 프로그램 에러 또는 오류라고 한다.
  + 컴파일 에러: 컴파일 시에 발생하는 에러
  + 런타임 에러: 실행 시에 발생하는 에러
  + 논리적 에러: 실행은 되지만, 의도와 다르게 동작하는 것
 
  + 에러(error): 프로그램 코드에 의해서 수습될 수 없는 심각한 오류(메모리 부족, 스택오버플로우 등)
  + 예외(exception): 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류
      
+ 1.2 예외 클래스의 계층구조
  + 자바에서는 실행 시 발생할 수 있는 오류(exception,error)를 클래스로 정의하였다.
  + 모든 클래스의 조상은 Object클래스이므로 Exception과 Error클래스 역시 Object클래스의 자손들이다.
  + 예외 클래스들은 다음과 같이 두 그룹으로 나눠질 수 있다.
    1. Exception클래스와 그 자손들
    2. RuntimeException클래스와 그 자손들
  + RuntimeException클래스들은 주로 프로그래머의 실수에 의해서 발생될 수 있는 예외들로 자바의 프로그래밍 요소들과 관계가 깊다.
  + Exception클래스들은 주로 외부의 영향으로 발생할 수 있는 것들로서, 프로그램의 사용자들의 동작에 의해서 발생하는 경우가 많다.
 
+ 1.3 예외처리하기 - try-catch문
  + 예외처리란, 프로그램 실행 시 발생할 수 있는 예기치 못한 예외의 발생에 대비한 코드를 작성하는 것이며, 예외처리의 목적은 예외의 발생으로 인한 실행 중인 프로그램의 갑작스런 비정상 종료를 막고, 정상적인 실행상태를 유지할 수 있도록 하는 것이다.
  + 발생한 예외를 처리하지 못하면, 프로그램은 비정상적으로 종료되며, 처리되지 못한 예외는 JVM의 '예외처리기'가 받아서 예외의 원인을 출력한다.
    ```
    try{
      // 예외가 발생할 가능성이 있는 문장들을 넣는다.
    } catch(Exception1 e1){
        //Exception1이 발생했을 경우, 이를 처리하기 위한 문장들을 넣는다.
    } catch(Exception2 e2){
        //Exception2이 발생했을 경우, 이를 처리하기 위한 문장들을 넣는다.
    } catch(ExceptionN eN){
        //ExceptionN이 발생했을 경우, 이를 처리하기 위한 문장들을 넣는다.
    }
    ```
  + 하나의 try블럭 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch블럭이 올 수 있으며, 이 중 발생한 예외의 종류와 일치하는 단 한개의 catch블럭만 수행된다.
 
+ 1.4 try-catch문에서의 흐름
  + try블럭 내에서 예외가 발생한 경우
    1. 발생한 예외와 일치하는 catch블럭이 있는지 확인한다.
    2. 일치하는 catch블럭을 찾게 되면, 그 catch블럭 내의 문장들을 수행하고 전체 try-catch문을 빠져나가서 그 다음 문장을 계속해서 수행한다. 만일 일치하는 catch블럭을 찾지 못하면, 예외는 처리되지 못한다.
  + try블럭 내에서 예외가 발생하지 않은 경우
    1. catch블럭을 거치지 않고 전체 try-catch문을 빠져나가서 수행을 계속한다.
 
+ 1.5 예외의 발생과 catch블럭
  + catch블럭은 괄호()와 블럭{} 두 부분으로 나눠져 있는데, 괄호()내에서는 처리하고자 하는 예외와 같은 타입의 참조변수 하나를 선언해야한다.
  + 예외가 발생하면, 발생한 예외에 해당하는 클래스의 인스턴스가 만들어지고, 첫 번째 catch블럭부터 차례로 내려가면서 catch블럭의 괄호()내에 선언된 참조변수의 종류와 생성된 예외클래스의 인스턴스에 instanceof 연산자를 이용하여 검사하게 되는데, 검사결과가 true인 catch블럭을 만날 때까지 검사는 계속된다.
  + 
